name: Run Tests and Publish Allure Report

on:
  push:
    branches:
      - lakshan-2
  pull_request:

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install Maven
        run: |
          sudo apt-get update
          sudo apt-get install -y maven

  api-tests:
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run API test JAR
        run: |
          java -jar demo-0.0.1-SNAPSHOT.jar &
          sleep 10 # Allow the server to start

      - name: Run Cucumber tests
        working-directory: ./api-testing-cucumber
        run: mvn clean test

      - name: Generate Allure report for Cucumber
        working-directory: ./api-testing-cucumber
        run: mvn allure:report

      - name: Copy Cucumber results
        run: |
          mkdir -p combined-results/allure-results
          cp -r api-testing-cucumber/target/allure-results/* combined-results/allure-results


  publish-report:
    needs: [api-tests]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy combined Allure report to GitHub Pages
        run: |
          allure generate --clean combined-results/allure-results -o combined-results/allure-report
          touch combined-results/allure-report/.nojekyll

      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: combined-results/allure-report
