name: Run Tests and Publish Allure Report

on:
  push:
    branches:
      - lakshan-2
  pull_request:

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install Maven
        run: |
          sudo apt-get update
          sudo apt-get install -y maven

  api-tests:
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run API test JAR
        run: |
          java -jar demo-0.0.1-SNAPSHOT.jar &
          sleep 10 # Allow the server to start

      - name: Run Cucumber tests
        working-directory: ./api-testing-cucumber
        run: mvn clean test
        continue-on-error: true # Do not fail the job on test failures

      - name: Generate Allure report for Cucumber
        working-directory: ./api-testing-cucumber
        run: mvn allure:report

  publish-report:
    needs: [api-tests]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Combine Allure Results
        if: always()
        run: |
          mkdir -p allure-results
          cp -r api-testing-cucumber/target/allure-results/* allure-results/ || true
          echo "Combined Results Content:"
          ls -R allure-results/
          echo "Total number of result files:"
          find allure-results -type f | wc -l

      - name: Generate Allure Report
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: allure-results
          allure_report: allure-report
          allure_history: allure-history

      - name: Deploy Allure Report
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
          publish_branch: gh-pages
          force_orphan: true
